version: "3.3"
services:

  web:
    # replace username/repo:tag with your name and image details
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"

