server.port: 8080

togglz.feature-enums: se.toggle.ToggleFeatures
togglz.console.enabled: true
togglz.console.path: /togglz-console
togglz.console.secured: false
togglz.console.use-management-port: false

spring.data.mongodb:
  host: db
  port: 27017
  database: features

spring.togglz.collection-name: togglz

